### ISSUE TITLE
File "convert.py", line 35, in convert     load_filtered_state_dict(model, saved_state_dict['model_state_dict']) KeyError: 'model_state_dict'

### ISSUE THREAD

**Issue by APeiZou** [thohemp/6DRepNet#11]
@thohemp    hello, 
python convert.py   6DRepNet_300W_LP_BIWI.pth    6DRepNet_300W_LP_BIWI_depoly.pth
errors:
File "convert.py", line 35, in convert
    load_filtered_state_dict(model, saved_state_dict['model_state_dict'])
KeyError: 'model_state_dict'

**Comment by thohemp** [comment]
Hi,
you try to deploy a model that is already deployed. The deploy script is for models that a generated by the training script.
