### ISSUE TITLE
How to train pre-train model

### ISSUE THREAD

**Issue by BenjaminGit001** [thohemp/6DRepNet#20]
Hi,
I tried to train the model from scratch, seems hard to train comparable performance as training model from the pre-train model.
My question is how to train the pre-train model or how to train the similar performance from scratch?

Thanks!

**Comment by thohemp** [comment]
I updated the default training settings. This should help you to achieve the reported results more easily (or in my trainings even surpass them). Let me know if you still struggle after using them.
