### ISSUE TITLE
Licence for Fine-tuned models

### ISSUE THREAD

**Issue by imae-sound** [thohemp/6DRepNet#27]
Hi.
Thanks for this interesting and wonderful piece of work!

I have a question about licensing, as the title says...
What would be the licence for Fine-tuned models?
Is it MIT like the codes, or is it different?

I want to use it as part of a work study, but I am not skilled in machine learning and would like to use the model as is!

I don't intend to publish, redistribute or incorporate them into products, but even if it is for research purposes, under my work rules, it is still a commercial use.
So, I would like to ask you for more information about the lisence for the models.

I look forward to response from you.
Thank you.

**Comment by thohemp** [comment]
Hi, 
the fine-tuned models are under MIT license, too.

Best regards
