### ISSUE TITLE
BIWI Dataset

### ISSUE THREAD

**Issue by janglinko-dac** [thohemp/6DRepNet#33]
Hey, 
I can not reproduce Your results on the BIWI Dataset.
Im comparing X Y Z angles obtained from the ground truth rotation matrix transformed by extrinsic calibration with -Pitch, Yaw and Roll repsectively. 
Im using Your pip package. I crop face with Retina Face detector as You do in demo.py and pass it to the model.predict() function. I instantiate model without any parameters, so the path to the weights are default.
I have spotted one difference. In the Readme You wirte 
```The BIWI datasets needs be preprocessed by a face detector to cut out the faces from the images. You can use the script provided [here](https://github.com/shamangary/FSA-Net/blob/master/data/TYY_create_db_biwi.py). For 7:3 splitting of the BIWI dataset you can use the equivalent script [here](https://github.com/shamangary/FSA-Net/blob/master/data/TYY_create_db_biwi_70_30.py). We set the cropped image size to 256.```
however, in the model.predict() the crop is resized to 244 (which i believe is longer edge of the picture, the shorter is then scaled with an appropriate ratio). Is it desired?

I can not find more differences, but mean error is about 25 on X and Y and about 8 on Z.
Can You help me figure it out?

Best,
Jan

**Comment by thohemp** [comment]
Hi,

we used 256 of the initial size to be able to augment the images by random cropping to its final size of 224. I suggest to make sure that the data preparation is done and no axis are accidentally switched. https://github.com/thohemp/6DRepNet/blob/master/sixdrepnet/datasets.py#L177

**Comment by janglinko-dac** [comment]
Thanks for the response,

I have identified axes using Your demo code. Im processing the BIWI dataset with this code too. I'm loading BIWI_70_30 model. I have noticed, that there are many persons on some pictures, thus i pick the area with the biggest face for each image.
The only difference from https://github.com/shamangary/FSA-Net/blob/4361d0e48103bb215d15734220c9d17e6812bb48/data/TYY_create_db_biwi.py#L40 is that in the demo code Retina Face detector is used instead of MTCNN. Results I obtain are:
![image](https://user-images.githubusercontent.com/106677088/203795270-3eab50a5-ee0d-43d3-a156-ca1ab4b081f9.png)

**Comment by thohemp** [comment]
What evaluation script do you use? I just tested this repo again and it gives me reported results:


```py
python test.py --dataset BIWI --filename-list /path/to/BIWI_70_30_test.npz --snapshot 6DRepNet_70_30_BIWI.pth
```
Output:
```console
Yaw: 2.6911, Pitch: 2.9193, Roll: 2.3557, MAE: 2.6553
```

**Comment by janglinko-dac** [comment]
Im using BIWI from HuggingFace. Im not using this preprocessing step from FSA-Net. 
Steps Im doing:
For each image in the BIWI:
1. from ground truth rotation matrix compute X Y Z angles.
2. Crop face with Retina Face detector
3. Add 0.4*size offset
4. Make predictions with 6DRepNet_70_30_BIWI.pth
5. Compute absolute error for each angle.
At the end, I compute MAE.

**Comment by thohemp** [comment]
I haven't used the BIWI data from HuggingFace. Hence, I can't tell where the problem lies. But the huggingface data won't have the same split as mine, so, by using my model, you are probably testing on part of the data the model is already trained on. So, either stick with my way on data preparation or completely retrain on a new model on your data.

**Comment by janglinko-dac** [comment]
I have followed Your steps and i got results as below:
```Yaw: 1.6349, Pitch: 1.8322, Roll: 1.7049, MAE: 1.7240```. 
However, I have found splitting script to be non deterministic, thus probably some of test data have been seen durning training.

**Comment by thohemp** [comment]
I won't share the dataset to not come in conflict with the corresponding license. Beyond that, my test data will give you different results, as your model is trained on different data. The script will provide you a dataset split, where training and test images are not the same. So it allows you to train the model yourself and generate similar results to mine.
