### ISSUE TITLE
Pretrained weight cannot be downloaded

### ISSUE THREAD

**Issue by skyrockets-21** [thohemp/6DRepNet#34]
Hi there, 

I am experimenting with the SixDRepNet_Detector and I am experiencing the issue that the model pretrained weight cannot be downloaded

here is the error message on Google Colab:

![image](https://user-images.githubusercontent.com/22537687/206884107-5ebe1f09-29dc-434a-945c-bd007611cf18.png)

Thank you!

**Comment by thohemp** [comment]
Hi, 
the link still works for me. Perhaps, the server was temporally down.

**Comment by skyrockets-21** [comment]
Good to know thank you!
