### ISSUE TITLE
Import error with pip package

### ISSUE THREAD

**Issue by craston** [thohemp/6DRepNet#41]
```
pip3 install sixdrepnet   #Works!
```

```
import sixdrepnet
```
I get the following error (I am currently running it on colab)

```
[/usr/local/lib/python3.8/dist-packages/sixdrepnet/regressor.py](https://localhost:8080/#) in <module>
      8 import numpy as np
      9 
---> 10 from model import SixDRepNet
     11 import utils
     12 

ModuleNotFoundError: No module named 'model'
```

**Comment by thohemp** [comment]
Have you tested this?

````py
# Import SixDRepNet
from SixDRepNet import SixDRepNet
import cv2

# Create model
# Weights are automatically downloaded
model = SixDRepNet()

img = cv2.imread('/path/to/image.jpg')

pitch, yaw, roll = model.predict(img)

model.draw_axis(img, yaw, pitch, roll)

cv2.imshow("test_window", img)
cv2.waitKey(0)```

**Comment by CemRoot** [comment]
Yeap still not working 
ModuleNotFoundError: No module named 'model' 
But I have already dowl. SixDRepNet

**Comment by thohemp** [comment]
I uploaded a new package that should solve this error:

`pip install sixdrepnet==0.1.5`

```sh
thorsten@thorsten:~/Projects/6DRepNet$ python 
Python 3.9.16 (main, Dec  7 2022, 01:12:08) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sixdrepnet
>>> from sixdrepnet import SixDRepNet
>>> model = SixDRepNet()
```

**Comment by CemRoot** [comment]
![image](https://user-images.githubusercontent.com/61415601/223082861-726007e6-0e2a-45a0-86e3-ce9c29efb07b.png)

**Comment by thohemp** [comment]
Pull the newest changes from github. You are currently executing the code from your local repo, not the pip package.

**Comment by CemRoot** [comment]
To much Error 
![image](https://user-images.githubusercontent.com/61415601/223141194-33227291-8569-4501-bc8a-8f7f956de1d7.png)

**Comment by CemRoot** [comment]
The project is not a working project, it does not work with new versions as far as I understand, so I pass this project.

Thanks for help

**Comment by thohemp** [comment]
Fix: https://github.com/thohemp/6DRepNet/commit/6dd8cf297c258dc80795756f3f38e38f19770b69

**Comment by craston** [comment]
Thanks! It works now.
