### ISSUE TITLE
Why did you set up the scheduler as MultiStepLR=False?

### ISSUE THREAD

**Issue by Algabri** [thohemp/6DRepNet#45]
I am not an expert on a scheduler, but I tried to understand it through [this one](https://androidkt.com/pytorch-change-the-learning-rate-based-on-epoch/).

Why did you set up the scheduler as MultiStepLR=False? 

I guess that is meaningless if we set up the scheduler as MultiStepLR=False.

Please, explain to me if I understood it wrong.

**Comment by thohemp** [comment]
You are correct. The scheduler is not used in training. It had no impact on the final accuracy of our model when we tested different configurations, so we deactivated it.

**Comment by Algabri** [comment]
@thohemp Thank you so much for your answer.
