### ISSUE TITLE
please tell me where 'output/snapshots/1.pth' in test.py

### ISSUE THREAD

**Issue by zxcvbnm12316** [thohemp/6DRepNet#47]
please tell me where 'output/snapshots/1.pth' in test.py

**Comment by zxcvbnm12316** [comment]
@thohemp  Hello, I can't find the 'output/snapshots/1.pth' file when I run the test.py file. Could you please provide this file? Thank you

**Comment by thohemp** [comment]
There is no file with this name. Stop spamming the issue section.

**Comment by zxcvbnm12316** [comment]
@thohemp 
I'm sorry to bother you again. The file ’ output/snapshots/1.pth ’ is indeed written in test.py. I can't find this file when I run test.py. Could you please provide this file? Thank you very much

`python test.py  --batch_size 64 \
                --dataset AFLW2000 \
                --data_dir datasets/AFLW2000 \
                --filename_list datasets/AFLW2000/files.txt \
                --snapshot output/snapshots/1.pth \
                --show_viz False`

**Comment by thohemp** [comment]
This line gives an example how to execute the script. Finetuned models are also linked in the readme a few lines above the that and can be downloaded for this usage.

**Comment by zxcvbnm12316** [comment]
> 此行给出了如何执行脚本的示例。微调模型也链接在上面几行的自述文件中，并且可以下载用于此用途。

Hello, I retrained the model and got the ‘’**_epoch.tar_**‘’ file. The pressurized file contains the ‘’**data.pkl**‘’ file, and the instance file shows the need for.‘**’pth**‘’ file. How do I get the**.pth_** file for snapshots,thank you。

Required in the document：
python test.py  --batch_size 64 \ --dataset AFLW2000 \ --data_dir datasets/AFLW2000 \ --filename_list datasets/AFLW2000/files.txt \ --snapshot **output/snapshots/1.pth** \ --show_viz False

I trained to get the files
_epoch_30 .tar    
Unzip the file, which contains the following three files
data  data.pkl  vwesion

**Comment by zxcvbnm12316** [comment]
> > 此行给出了如何执行脚本的示例。角色模型也链接在上面几行描述的自文件中，并且可以下载用于此用途。
> 
> 您好，我重新训练了模型并获得了“ **_epoch.tar_** ”文件。加压文件包含“ **data.pkl** ”文件，实例文件显示需要。**'pth** '' 文件。如何获取快照的**.pth_**文件，谢谢。
> 
> 文档中必填： python test.py --batch_size 64 \ --dataset AFLW2000 \ --data_dir datasets/AFLW2000 \ --filename_list datasets/AFLW2000/files.txt \ --snapshot **output/snapshots/1.pth** \ --show_viz False
> 
> 我训练得到文件 _epoch_30 .tar 解压该文件，其中包含以下三个文件 数据 data.pkl vwesion

@thohemp
